/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bil481Hw1;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

class AppTest {
    @Test
    public void testSortAscending(){
        int[] numbers = {3,8,7,1,2};
        int[] expected = {1,2};
        assertTrue(Arrays.equals(App.sortCut(numbers, 2, true), expected));
    }
    @Test
    public void testSortDescending(){
        int[] numbers = {4,5,11,25,1};
        int[] expected = {25,11,5};
        assertTrue(Arrays.equals(App.sortCut(numbers, 3, false), expected));
    }
    @Test
    public void testEmptyList(){
        int[] numbers = new int[3];
        assertTrue(Arrays.equals(App.sortCut(numbers, 3, false), numbers));
    }
    @Test
    public void testIndexOutOfBoundsException(){
        int[] numbers = {3,5,8};
        assertThrows(IndexOutOfBoundsException.class, () -> { App.sortCut(numbers, 10, true); });
    }

    @Test
    public void testFullList(){
        int[] numbers = {3,22,19,105,99};
        int[] expected = {3,19,22,99,105};
        assertTrue(Arrays.equals(App.sortCut(numbers, numbers.length, true),expected));
    }

}

