/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bil481Hw1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static int[] sortCut(int numArr[], int quantifier, boolean inc) 
    { 
        if(numArr.length == 0)
        {
            return numArr;
        }
        int[] result = new int[quantifier];
        int n = numArr.length;
        if(inc == true){
            for (int i = 0; i < n-1; i++){
                int min = i; 
                for (int j = i+1; j < n; j++) 
                    if (numArr[j] < numArr[min])
                        min = j; 
                int temp = numArr[min]; 
                numArr[min] = numArr[i]; 
                numArr[i] = temp;
            }
        }
        else{
            for (int i = 0; i < n-1; i++){
                int max = i; 
                for (int j = i+1; j < n; j++) 
                    if (numArr[j] > numArr[max])
                        max = j; 
                int temp = numArr[max]; 
                numArr[max] = numArr[i]; 
                numArr[i] = temp;
            }
        }
        for(int i = 0; i < quantifier; i++){
            result[i] = numArr[i];
        }
        return result;
    } 
}    

